version: '3.9'
services:
  redis:
    image: redis:7.0.5-alpine
    networks:
      - redis-net
    ports:
      - 6379:6379
    volumes: 
      - redis-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:15.1-alpine
    user: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
       - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - postgres-net
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    build:
      context: ./nginx
      target: development
    networks:
      - nginx-net
    ports:
      - 80:80
    restart: unless-stopped

  api_gateway:
    build:
      context: ./src
      dockerfile: ./.docker/api-gateway.Dockerfile
      target: development
    ports:
      - 8080:8080
    networks:
      - postgres-net
      - redis-net
      - nginx-net
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}

  migration:
    build:
      context: ./src
      dockerfile: ./.docker/migration.Dockerfile
      target: development
    restart: on-failure
    networks:
      - postgres-net
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}

volumes:
  postgres-data:
  redis-data:
  pgadmin-data:

networks:
  postgres-net:
  redis-net:
  nginx-net:

secrets:
  nginx-cert:
    external: true
  nginx-key:
    external: true
